import { existsSync, readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

const GLOBALS = 'src/app/globals.css'

/**
 * `globals.css` imports one generated stylesheet (`tokens.css`, written by
 * `scripts/build-tokens.ts`) and one authored one (`motion.css`). A missing import is not a
 * soft failure: Turbopack reports `Can't resolve '../styles/…'` and the dev server returns
 * 500, with an error that points at globals.css line 1 rather than at the real cause.
 *
 * `pnpm build` and `pnpm test` were always safe because `prebuild` and `pretest` regenerate
 * the tokens. `pnpm dev` had no such hook, so it was the one uncovered entry point.
 */
describe('globals.css imports resolve on disk', () => {
  const source = readFileSync(GLOBALS, 'utf8')
  const relativeImports = [...source.matchAll(/@import\s+['"](\.[^'"]+)['"]/g)].map((m) => m[1])

  it('imports at least the token and motion stylesheets', () => {
    expect(relativeImports).toContain('../styles/tokens.css')
    expect(relativeImports).toContain('../styles/motion.css')
  })

  it.each(
    [...new Set([...source.matchAll(/@import\s+['"](\.[^'"]+)['"]/g)].map((m) => m[1]))],
  )('resolves %s', (importPath) => {
    const absolute = resolve(dirname(GLOBALS), importPath)
    expect(existsSync(absolute), `${importPath} does not exist at ${absolute}`).toBe(true)
  })
})

describe('the generated stylesheet is regenerated for every entry point', () => {
  const pkg = JSON.parse(readFileSync('package.json', 'utf8')) as {
    scripts: Record<string, string>
  }

  it.each(['predev', 'prebuild', 'pretest'])(
    '%s regenerates design tokens before the command runs',
    (hook) => {
      expect(pkg.scripts[hook], `${hook} hook is missing`).toContain('tokens:build')
    },
  )

  it('keeps tokens.css generated rather than hand-edited', () => {
    expect(readFileSync('src/styles/tokens.css', 'utf8')).toContain('GENERATED by')
  })
})
