import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import color from '../tokens/color.json'
import typography from '../tokens/type.json'
import space from '../tokens/space.json'
import { contrastRatio, shift } from './lib/derive'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')

export function buildTokens() {
  const app: Record<string, string> = {}
  const lines: string[] = []

  for (const [name, def] of Object.entries(color.base)) {
    lines.push(`  --color-${name}: ${def.value};`)
    app[`color.${name}`] = def.value
    for (const [variant, amount] of Object.entries(color.derive)) {
      lines.push(`  --color-${name}-${variant}: ${shift(def.value, amount)};`)
    }
  }

  for (const [state, def] of Object.entries(color.charge)) {
    lines.push(`  --color-charge-${state}: ${def.value};`)
    lines.push(`  --color-charge-${state}-border: ${shift(def.value, color.derive.border)};`)
    app[`color.charge.${state}`] = def.value
  }

  for (const [key, value] of Object.entries(typography.families)) {
    lines.push(`  --font-${key}: ${value};`)
    app[`font.${key}`] = value
  }
  for (const [key, value] of Object.entries(typography.scale)) {
    lines.push(`  --text-${key}: ${value};`)
    app[`text.${key}`] = value
  }
  for (const [key, value] of Object.entries(typography.weight)) {
    lines.push(`  --weight-${key}: ${value};`)
  }
  for (const [key, value] of Object.entries(typography.leading)) {
    lines.push(`  --leading-${key}: ${value};`)
  }
  for (const [key, value] of Object.entries(space.space)) {
    lines.push(`  --space-${key}: ${value};`)
    app[`space.${key}`] = value
  }
  for (const [key, value] of Object.entries(space.radius)) {
    lines.push(`  --radius-${key}: ${value};`)
    app[`radius.${key}`] = value
  }

  const css = [
    '/* GENERATED by scripts/build-tokens.ts — do not edit. Edit tokens/*.json. */',
    ':root {',
    ...lines,
    '}',
    '',
  ].join('\n')

  const figma = {
    collections: [
      {
        name: 'Adhara Colour',
        modes: ['Light'],
        variables: Object.entries(app)
          .filter(([k]) => k.startsWith('color.'))
          .map(([k, v]) => ({ name: k, type: 'COLOR', valuesByMode: { Light: v } })),
      },
      {
        name: 'Adhara Space',
        modes: ['Default'],
        variables: Object.entries(app)
          .filter(([k]) => k.startsWith('space.') || k.startsWith('radius.'))
          .map(([k, v]) => ({ name: k, type: 'FLOAT', valuesByMode: { Default: v } })),
      },
    ],
  }

  return { css, figma, app }
}

/** Fails the build rather than shipping an inaccessible palette. */
function assertContrast() {
  const checks: [string, string, number, string][] = [
    ['#14201B', '#F4F6F1', 4.5, 'ink on mist'],
    ['#FFFFFF', '#0E3B2E', 4.5, 'white on forest'],
    ['#14201B', '#E8A020', 4.5, 'ink on turmeric'],
  ]
  for (const [a, b, min, label] of checks) {
    const ratio = contrastRatio(a, b)
    if (ratio < min) {
      throw new Error(`Contrast failure: ${label} is ${ratio.toFixed(2)}:1, needs ${min}:1`)
    }
  }
}

function main() {
  assertContrast()
  const { css, figma, app } = buildTokens()
  mkdirSync(resolve(root, 'src/styles'), { recursive: true })
  mkdirSync(resolve(root, 'exports'), { recursive: true })
  writeFileSync(resolve(root, 'src/styles/tokens.css'), css)
  writeFileSync(resolve(root, 'exports/figma-variables.json'), JSON.stringify(figma, null, 2))
  writeFileSync(resolve(root, 'exports/app-tokens.json'), JSON.stringify(app, null, 2))
  console.log('tokens: wrote tokens.css, figma-variables.json, app-tokens.json')
}

if (process.argv[1] && process.argv[1].includes('build-tokens')) main()
